version: "3.9"
services:
  postgres:
    image: "postgres"
    environment: 
      POSTGRES_PASSWORD: nestjscourse
    ports:
      - "5432:5432"
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: johndoe@example.org
      PGADMIN_DEFAULT_PASSWORD: nestjscourse
    ports:
      - "80:80"
